---
title: 岭回归学习
author: Sheng Luan
date: '2021-05-17'
slug: ridge-regression
categories:
  - 统计
tags:
  - Ridge regression
---
1 前言

之前一直接触的是BLUP、ssGBLUP等方法，对于岭回归、贝叶斯等方法了解甚少。最近在做抗病性状的遗传评估，需要了解和评估相关算法，先从岭回归学起。

基因组选择需要解决的问题：

* 在早期，SNP标记的数量要远大于样本量，这意味着要求解的标记效应值数量远大于观察值，会存在不唯一的解。针对这个问题，提出了[RRBLUP](https://doi.org/10.3835/plantgenome2011.08.0024)的方案。
* 但是现在问题反过来了，像奶牛分型的样本量已经达到了百万头，已经比一般的芯片，如50K要多了。现在问题是如何求解对如此庞大的样本，求解其逆矩阵。[Misztal](https://doi.org/10.3168/jds.2013-7752)等人提出了APY算法策略，即把分型个体分为核心和非核心两类，利用少量核心个体的基因组亲缘关系逆矩阵，以及非核心与核心个体间的基因组亲缘关系矩阵，直接计算得到所有分型个体的基因组亲缘关系逆矩阵，避免了直接求逆。具体可参考ssGBLUP方法的最新综述文章：[Single-Step Genomic Evaluations from Theory to Practice: Using SNP Chips and Sequence Data in BLUPF90](https://doi.org/10.3390/genes11070790)。

本文主要想了解两个问题：

* 为什么讲RRBLUP等价于GBLUP
* RRBLUP是如何解决p>n问题的

本文主要是学习RRBLUP方法，参考了[百奥云GS专栏的基因组选择之模型篇](https://www.cnblogs.com/jessepeng/p/14375487.html)的相关叙述，感觉说的特别好。

RRBLUP vs GBLUP

* RRBLUP是一种改良的最小二乘法，是间接法的代表算法。它能估计出**所有SNP的效应值**。该方法将标记效应假定为**随机效应**且服从**正态分布**，利用**线性混合效应模型**估算每个标记的效应值，然后将每个标记效应相加即得到个体的估计育种值。

* GBLUP是直接法的代表，它把**个体**作为随机效应，根据参考群体和预测群体SNP基因型信息构建的亲缘关系矩阵作为方差协方差矩阵，通过迭代法估计方差组分，进而求解线性混合效应模型获得待预测个体的估计育种值。

2 模型

考虑到Endelman等RRBLUP的文章中，公式中对G的定义跟后来的基因组亲缘关系G矩阵冲突，这里采用Hayes等文章中的定义方法。

2.1 RRBLUP模型（以标记为基础的BLUP）:

$$y=ZWu+e$$
其中，$u \sim N(0,I\sigma^{2}_{u})$，u为标记等位基因的替代效应向量；W是基因型矩阵（-1,0,1等形式）；Z为观察值的关联矩阵。

假定$K=ZW$，那么标记效应的BLUP解为:
$$\hat{u}=(K'K+\lambda I)^{-1}K'y$$
其中I表示标记间是独立的，没有连锁关系。岭参数$\lambda = \sigma^{2}_{e}/\sigma^{2}_{u}$为残差方差与标记效应方差的比值。

上述公式可以根据经典的单性状BLUP模型公式推导：
$$
\begin{bmatrix}
X'X & X'K \\ 
K'X & K'K+\lambda I 
\end{bmatrix}
\begin{bmatrix}
\hat{b} \\ 
\hat{u}  
\end{bmatrix}
=
\begin{bmatrix}
X'y \\
K'y
\end{bmatrix}
$$
由于没有模型中没有考虑固定效应，因此模型可以进一步简化为
$$
(K'K+\lambda I)\hat{u} = K'y
$$
进而推导出前述公式。

2.2 常规BLUP模型

$$y=Zg+e$$
其中，$g \sim N(0,G\sigma^{2}_{g})$，g为基因型值向量；Z为观察值的关联矩阵。

注意：RRBLUP模型中标记效应指的是每个位点**某个等位基因的可替代效应**；而常规BLUP模型中基因型值指的**所有位点的基因型值之和**，即个体水平的效应。

在系谱为基础的育种值预测过程中，G指的是根据共亲系数计算得到的加性亲缘关系矩阵**A**。

从2个模型中可以看出$g=Wu$，基因型值即个体育种值的遗传方差：

$$V(g)=G\sigma^{2}_{g}=V(Wu)=WW'\sigma^{2}_{u}$$
如上所述，**这两个模型是等同的**。

因此，G矩阵也可以根据W矩阵计算得到：

$G = WW'\sigma^{2}_{g}/\sigma^{2}_{u}$。此时，G为基因组亲缘关系矩阵。

因此，$G$的另外一个特性：基于该矩阵计算得到的GEBV**等同于**利用RRBLUP模型计算得到的结果。


