---
title: data.table自带例子注解
author: Sheng Luan
date: '2019-09-14'
slug: the-examples-in-data-table
categories:
  - R
tags:
  - Data.table
output: html_document
---

加载data.table包后，运行**example("data.table")**可以获得data.table自带的例子代码。本文对代码的意思进行了中文注释，以深入理解data.table的特性。

```{r}
library(data.table)
```

## 1.生成数据集
生成DF和DT数据集，类型分别为data frame和data.table。二者本质上均为**list**类型。
```{r}
DF = data.frame(x=rep(c("b","a","c"),each=3), y=c(1,3,6), v=1:9)
DT = data.table(x=rep(c("b","a","c"),each=3), y=c(1,3,6), v=1:9)
DF
DT
identical(DF$a, DT$a) 
is.list(DF)
is.list(DT)
```
## 2.行操作
```{r}
DT[2]                          # 提取第二行数据
DT[3:2]                        # 提取第三行和第二行数据
DT[order(x)]                   # 根据x升序对DT进行排序
DT[order(x), ]                 # 这样写也可以，不如上一行简洁
DT[y>2]                        # 提取所有y>2 的行
DT[y>2 & v>5]                 # 提取满足条件：y> 2 并且 v> 5的行
DT[!2:4]                      #提取除2, 3,4行外的其他行
DT[-(2:4)]                   #同上
```

## 3.列操作
```{r}
DT[, v]                      #提取列名为v的该列所有值，返回一个向量
DT[, list(v)]                #提取列名为v的该列所有值，返回一个data.table
DT[, .(v)]                  #同上，.()是list()的缩写
DT[, sum(v)]                #列v所有值的和，返回一个向量
DT[, .(sum(v))]             #同上，返回一个data.table
DT[, .(sv=sum(v))]          #同上，但列被命名为sv
DT[, .(v, v*2)]             #返回一个data.table，包括两列：v和2v
```

## 4.对部分行进行列操作
譬如，仅对2,3行v列进行求和操作。
```{r}
DT[2:3, sum(v)]
DT[2:3, .(sum(v))]
DT[2:3, .(sv=sum(v))] 
DT[2:5, cat(v, "\n")]
```

## 5.通过data frame方式选择列
```{r}
DT[, 2]               #通过数字方式选择列，返回一个data.table
col_num = 2
DT[, ..col_num]       #..后跟随变量表示该变量名不是DT中的某一列，它存储的值为DT中的列名。
DT[["y"]]             #同DT[, y]，返回向量，但读取速度更快
```
## 6.分组操作
```{r}
DT[, sum(v), by=x]              #根据x进行分组，每组求v列的和
DT[, sum(v), keyby=x]           #同上，但输出结果根据x排序
DT[, sum(v), by=x][order(x)]    #同上，通过链式排序
```

